rabbitmq:
    url: localhost:5672
    vhost: /test
    username: guest
    password: guest
    exchanges:
        order:
            name: order
            type: topic
            auto-delete: false
            number-consumers: 3
            number-retries: 3
            redelivery-delay: 3000
            maximum-redeliveries: -1



