rabbitmq:
    url: localhost:5672
    vhost: /test
    username: guest
    password: guest
    queue: order.queue
    exchanges:
        order:
            name: order
            type: topic
            auto-delete: false


